<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Resizable_ui-resizable-handle ui-resiza_9242df</name>
   <tag></tag>
   <elementGuidId>0ba1dade-7ca5-4628-b940-af16b787e37f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='resizable']/div[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.ui-resizable-handle.ui-resizable-se.ui-icon.ui-icon-gripsmall-diagonal-se</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9e4e9d08-19b9-4c1c-ad72-ad16b48b24df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-resizable-handle ui-resizable-se ui-icon ui-icon-gripsmall-diagonal-se</value>
      <webElementGuid>096968e1-7c0f-4a1c-a542-96547bf20417</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;resizable&quot;)/div[@class=&quot;ui-resizable-handle ui-resizable-se ui-icon ui-icon-gripsmall-diagonal-se&quot;]</value>
      <webElementGuid>3afb00f2-0ed9-48f1-9909-577dc165c43c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='resizable']/div[3]</value>
      <webElementGuid>4ef98e8d-aa49-48ed-83ff-641a40eb562b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div[3]</value>
      <webElementGuid>9a8329a6-8d87-4727-a2aa-68654c5c3f7e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
