<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Powered by_svg</name>
   <tag></tag>
   <elementGuidId>0761bdff-21fc-4552-9660-f765adc2ddb1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='FSForm']/div[2]/div[27]/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.svg</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>7434cd49-7870-4863-b60f-b020220a1648</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>be062045-54d3-41fc-ada9-c3923b22d6a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/images/layout/external/formsite_logo.svg</value>
      <webElementGuid>1c5cd2cf-5a0b-4a48-ace1-80db4fea744b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Formsite</value>
      <webElementGuid>f6dd4a8f-03ce-4c10-9f23-33a8c569ba05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FSForm&quot;)/div[@class=&quot;form_table&quot;]/div[27]/a[1]/img[@class=&quot;svg&quot;]</value>
      <webElementGuid>d35620d5-9f37-4e24-9148-f78fd3c8fded</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Automation Testing Practice/iframe_Automation Testing Practice_frame-on_f39fe2</value>
      <webElementGuid>1815c6af-740f-4e63-8754-bd1833bef052</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='FSForm']/div[2]/div[27]/a/img</value>
      <webElementGuid>f40ce4bf-023a-4eee-8a81-ac3ec641d0f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Formsite']</value>
      <webElementGuid>b81f90d2-113f-4f58-b664-3bc68175bb0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>f79e5089-e728-448d-91f2-86483e9ef0f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/images/layout/external/formsite_logo.svg' and @alt = 'Formsite']</value>
      <webElementGuid>afefd6c6-fcaa-4b17-b8c0-c77aeba09ada</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
